name: Terraform Destroy

on:
  workflow_dispatch:  # Cho phép chạy workflow thủ công khi cần destroy

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    name: Destroy Infrastructure with Terraform

    steps:
      # 1. Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Thiết lập AWS credentials cho Terraform
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Thiết lập Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6 # Thay bằng phiên bản Terraform bạn cần

      # 4. Khởi tạo Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # 5. Thực hiện hủy cơ sở hạ tầng với Terraform
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform
