name: Terraform Destroy

on:
  workflow_dispatch:  # Cho phép chạy workflow thủ công khi cần destroy

permissions:
  id-token: write
  contents: read
jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    name: Destroy Infrastructure with Terraform

    steps:
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout repository
        uses: actions/checkout@v1
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5q.5

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
